[build]
  base = "/"
  command = "npm ci && npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20"
  VITE_API_URL = "https://reservas-peluqeria.onrender.com"
  VITE_GOOGLE_CLIENT_ID = "tu-google-client-id"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
  command = "npm run dev"
  port = 5173
  publish = "dist"
